application:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
server:
  port: 8080
logging:
  level:
    root: info
    net.ttddyy.dsproxy.listener: info
spring:
  application:
    name: mentality
  datasource:
    hikari:
      auto-commit: false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 2048
        connection:
          provider_disables_autocommit: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  threads:
    virtual:
      enabled: true