server.port: 8080
logging.level:
  net.ttddyy.dsproxy.listener: info
  web: info
  root: info
  liquibase: info
spring:
  application:
    name: mentality
  datasource:
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOMAIN}:${PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 2048
        connection:
          provider_disables_autocommit: true
application:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
