name: CI pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]
jobs:
  build:
    name: Build and Analyze
    runs-on: [ ubuntu-latest ]
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: admin
          POSTGRES_DB: mentality_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Test
        run: mvn -B install sonar:sonar -Pcoverage -Dsonar.projectKey=MinoUni_tc-mentality
